"""empty message

Revision ID: 5352096b5a7a
Revises: 
Create Date: 2026-02-02 01:19:58.313776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5352096b5a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.String(length=180), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('use', sa.String(length=180), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('town', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user')
    )
    op.create_table('favorites_table',
    sa.Column('Location_id', sa.Integer(), nullable=True),
    sa.Column('Character_id', sa.Integer(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['Location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_table')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('character')
    # ### end Alembic commands ###
